global class SandboxInfo {
    
    global Id Id;
	global Id ApexClassId;
	global Boolean AutoActivate = true;
	global String Description='';
    global Integer HistoryDays=0;
    global Boolean IsNonPreview=false;
    global Boolean IsPreRelease=false;
    global Boolean IsPreview=false;
    global String LicenseType;
    global String SandboxName;
    global Id SourceId;
    global Id TemplateId;
    global DateTime CreatedDate;
    global DateTime LastModifiedDate;
	
	
}